# Generated by Django 4.2 on 2025-02-27 14:51

from django.db import migrations, models
import userauths.models


class Migration(migrations.Migration):

    dependencies = [
        ('userauths', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default-profile.jpg', null=True, upload_to=userauths.models.user_directory_path),
        ),
    ]
