# Generated by Django 4.2 on 2024-10-29 13:24

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='gallery_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=5, max_length=10, prefix=''),
        ),
    ]
