# Generated by Django 4.2 on 2024-10-30 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_remove_category_image_category_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='weight',
        ),
    ]
