# Generated by Django 4.2 on 2024-10-31 10:12

from django.db import migrations
import shortuuid.django_fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_product_life'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=8, max_length=10, prefix='', unique=True),
        ),
    ]
